apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodebb-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeName: nodebb-pv
